### 1️⃣ Criar um post salvo
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id_user": "456",
  "ativo": true,
  "noticia": {
    "id": "123",
    "titulo": "Nova descoberta científica",
    "conteudo": "Detalhes da notícia aqui..."
  }
}

### 2️⃣ Buscar post por ID (chave Redis gerada)
GET http://localhost:8080/api/posts/findById/post:123:user:456
Accept: application/json
